# Generated by Django 2.1 on 2020-05-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserActions', '0002_auto_20200530_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.AutoField(default=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
