# Generated by Django 2.1 on 2020-05-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserActions', '0002_remove_userattribute_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Vegetable', max_length=100),
            preserve_default=False,
        ),
    ]
